export const CONFIG = {
  DEFAULT_METHOD: 'GET',
  DEFAULT_TIMEOUT: 10000,
  DEFAULT_EXPECTED_STATUS: 200,
  HEALTH_CHECK_LIMIT: 1440,
  UPTIME_CALCULATION_LIMIT: 100,
} as const;

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
} as const;
